dot.print("start lua script...")

local zig_boilerplate = [[
// Boilerplate generated by  Lua !
const std = @import("std");

pub fn main() !void {
    std.debug.print("Hello from dot.!\n", .{});
}
]]

dot.insert(zig_boilerplate)

dot.insert("\n //- List")

for i = 1, 5 do
	local line = "// -> elem n<" .. tostring(i) .. ">\n"
	dot.insert(line)
end

dot.print("script finished !")
